default_stages: [commit]
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
-   repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
    -   id: black
        args: ['--line-length', '110']
-   repo: https://github.com/pycqa/flake8
    rev: 3.7.3
    hooks:
    -   id: flake8
        args:
          - "--max-line-length=110"
          - "--exclude=.*,alembic/*,*/snapshots/snap_*.py,apps/users/apps.py"
          - "--ignore=W503"
