# Generated by Django 4.2.3 on 2023-07-23 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                ("last_login", models.DateTimeField(blank=True, null=True, verbose_name="last login")),
                (
                    "email",
                    models.EmailField(
                        db_index=True,
                        error_messages={"unique": "User with this email already exist."},
                        max_length=254,
                        unique=True,
                    ),
                ),
                ("first_name", models.CharField(max_length=250)),
                ("last_name", models.CharField(max_length=250)),
                (
                    "phone_number",
                    models.BigIntegerField(
                        error_messages={"unique": "User with this email already exist."}, unique=True
                    ),
                ),
                ("birthday", models.DateField(null=True)),
                ("is_active", models.BooleanField(default=False)),
                ("blocked", models.BooleanField(default=False)),
                ("email_verified", models.BooleanField(default=False)),
            ],
            options={
                "db_table": "users",
            },
        ),
    ]
