# Generated by Django 4.2.3 on 2023-08-14 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("wish_list", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="wishlist",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="wishlist",
            name="modified_at",
        ),
        migrations.RemoveField(
            model_name="wishlistproducts",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="wishlistproducts",
            name="modified_at",
        ),
    ]
